### ISSUE TITLE
When React-motion meet Redux, what to do?

### ISSUE THREAD

**Issue by wuxianliang** [hayeah/react-motion-SortableList#1]
Dear @hayeah:
  This is a good demo, thank you. Two days ago, I tried to modify this demo with Redux, but I quit. I have to admit I have not understood these two new projects. One question makes me confused is how to tackle state and store. There is unique state in store, but what about the states from React-motion? If you are interested in this topic, I suggest you keep going. It would help a lot. Thank you very much.

https://github.com/AdamBrodzinski/meteor-flux-leaderboard/issues/4 there is one more developer cares about this topic.

**Comment by hayeah** [comment]
In react-native, `<Spring key={key} {...otherProps}>` uniquely identifies an animated component. As long as the key stays the same, React's reconciliation algorithm would assign changed props to the same component, causing the Spring component's animation to start.

So if you need to get data out of Redux, you just need to assign each data item a unique ID.
